### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by trf000**
Calendar and Pagesmith - Editor generated in Modal cannot get focus in popovers with form elements.

Not sure what the Merge remote-tracking branch change is. must have been an old file or something. I'd ignore it.

### CODE REVIEW

**Comment by jlbooker** [comment]
That "Merge remote-tracking branch" commit is actually a really big merge. So big that GitHub won't show it all (300 files, 4k additions, 6k deletions). It looks like you may have been merging in changes from our master, but I'd still be nervous about merging all that in. I think you wanted to `git pull --rebase upstream master`.

**Comment by jlbooker** [comment]
Refs #255

**Comment by trf000** [comment]
I wasn't sure how that got in there, didn't notice it when i made the pull request. Want me to do the request again without that in there?

**Comment by trf000** [comment]
Except for the change to properties module, the other four are fairly minor, but pretty necessary.

**Pull request closed without merging**
